parameters:
    twig.path: '%app.path%/templates'
    twig.options:
        charset: 'UTF-8'
        debug: false
        strict_variables: false
        cache: '%app.cache_path%/twig'
        auto_reload: true

services:
    twig.trans:
        class: Symfony\Bridge\Twig\Extension\TranslationExtension
        arguments: [ "@translator" ]

    twig.md5sum:
        class: App\Twig\Extension\Md5sum
        arguments: [ "%app.path%/../" ]

    twig.loader:
        class: Twig_Loader_Filesystem
        arguments: [ "%twig.path%" ]

    twig:
        class: Twig_Environment
        arguments: [ "@twig.loader", "%twig.options%" ]
        calls:
            - [ addGlobal, [ 'debug', "%app.debug%" ] ]
            - [ addGlobal, [ 'app_name', "%app.name%" ] ]
            - [ addGlobal, [ 'app_version', "%app.version%" ] ]
            - [ addGlobal, [ 'app_url', "%app.url%" ] ]
            - [ addGlobal, [ 'locale', "%app.locale%" ] ]
            - [ addExtension, [ '@twig.md5sum' ] ]
            - [ addExtension, [ '@twig.trans' ] ]